-- Latest game day's scores and goal-by-goal scoring summary for the score ticker (issue #42).
-- Rewritten by the data job on every sync; only the most recent game days are kept.

CREATE TABLE scoreboard_games (
    game_id BIGINT PRIMARY KEY,
    game_date VARCHAR(255) NOT NULL,
    season_id VARCHAR(255),
    start_time_utc VARCHAR(255),
    game_state VARCHAR(255),
    away_team_code VARCHAR(255),
    away_score INTEGER,
    home_team_code VARCHAR(255),
    home_score INTEGER,
    last_period_type VARCHAR(255),
    last_updated TIMESTAMP(6)
);

CREATE INDEX idx_scoreboard_games_game_date ON scoreboard_games (game_date);

CREATE TABLE scoreboard_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES scoreboard_games (game_id) ON DELETE CASCADE,
    goal_number INTEGER NOT NULL,
    period INTEGER,
    period_type VARCHAR(255),
    time_in_period VARCHAR(255),
    team_code VARCHAR(255),
    scorer_id BIGINT,
    scorer_name VARCHAR(255),
    assist1_id BIGINT,
    assist1_name VARCHAR(255),
    assist2_id BIGINT,
    assist2_name VARCHAR(255),
    away_score INTEGER,
    home_score INTEGER,
    strength VARCHAR(255)
);

CREATE INDEX idx_scoreboard_goals_game_id ON scoreboard_goals (game_id);
